# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_miw-1AVC1yTxppCroeyQ8HLmNyQAnFq
"""

import math

def analyze_linkage(r_2, r_3, r_d, theta_2_deg, omega_2, alpha_2):
    theta_2 = math.radians(theta_2_deg)
    theta_3 = math.asin((r_d - r_2 * math.sin(theta_2)) / r_3)

    r_1 = r_2 * math.cos(theta_2) + r_3 * math.cos(theta_3)

    omega_3 = -(r_2 * omega_2 * math.cos(theta_2)) / (r_3 * math.cos(theta_3))
    v_1 = -r_2 * omega_2 * math.sin(theta_2) - r_3 * omega_3 * math.sin(theta_3)

    alpha_3 = (r_2 * omega_2**2 * math.sin(theta_2) - r_2 * alpha_2 * math.cos(theta_2) + r_3 * omega_3**2 * math.sin(theta_3)) / (r_3 * math.cos(theta_3))
    a_1 = -r_2 * omega_2**2 * math.cos(theta_2) - r_3 * omega_3**2 * math.cos(theta_3) - r_2 * alpha_2 * math.sin(theta_2) - r_3 * alpha_3 * math.sin(theta_3)

    return r_1, theta_3, omega_3, v_1, alpha_3, a_1